baseURL = 'https://planet.clermontech.org/'
languageCode = 'fr-FR'
title = "Planet Clermont'ech"
theme = 'hyde-custom'

[params]
description = "Retrouvez tous les événements du monde IT Auvergnat !"

[Menus]
main = [
    {Name = "Accueil", URL = "https://planet.clermontech.org", Weight = 1},
    {Name = "Clermont'ech", URL = "https://clermontech.org/", Weight = 2},
    {Name = "RSS", URL = "/index.xml", Weight = 3},
]


[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

